# 线上配置文件
#  
#  
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.144.106:3306/mianjingtong
    username: mianjingtong
    password: zwj..622
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 62.234.144.106
    port: 6379
    timeout: 5000
    password: zwj..622
#  # Elasticsearch 配置
#  # todo 需替换配置
#  elasticsearch:
#    uris: http://62.234.144.106:9200
#    username: root
#    password: zwj..622
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: zwj..622
